export const TAG = {
  Advertisement: 'Advertisement',
  Adult: 'Adult',
  AudioStreaming: 'Audio Streaming',
  Career: 'Career',
  CDN: 'CDN',
  CloudService: 'Cloud Service',
  Collaboration: 'Collaboration',
  Community: 'Community',
  Cryptocurrency: 'Cryptocurrency',
  Design: 'Design',
  Development: 'Development',
  DIYCraft: 'DIY & Craft',
  ECommerce: 'E-Commerce',
  Educational: 'Educational',
  Entertainment: 'Entertainment',
  Email: 'Email',
  FinanceBanking: 'Finance & Banking',
  FoodCooking: 'Food & Cooking',
  Forum: 'Forum',
  Government: 'Government',
  HealthFitness: 'Health & Fitness',
  Media: 'Media',
  News: 'News',
  NonProfitCharity: 'Non-Profit & Charity',
  OnlineGaming: 'Online Gaming',
  PersonalBlog: 'Personal Blog',
  Photography: 'Photography',
  Productivity: 'Productivity',
  ProfessionalService: 'Professional Service',
  RealEstate: 'Real Estate',
  RegionalLocalService: 'Regional & Local Service',
  SearchEngine: 'Search Engine',
  SocialNetwork: 'Social Network',
  SoftwareDownload: 'Software Download',
  Sport: 'Sport',
  Technology: 'Technology',
  TravelTourism: 'Travel & Tourism',
  Vehicles: 'Vehicles',
  VideoStreaming: 'Video Streaming',
  WebApp: 'Web App',
  Weather: 'Weather',

  Other: 'Other',
  Unknown: 'Unknown',
};
